import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';
import { gql } from 'graphql-request';

// Custom base query for GraphQL API
const graphqlBaseQuery = ({ baseUrl }) => async ({ body }) => {
  try {
    const response = await fetch(baseUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(body),
    });

    if (!response.ok) {
      throw new Error('Network response was not ok');
    }

    const data = await response.json();
    return data;

  } catch (error) {
    return { error: { status: 500, data: error.message } };
  }
};

// Create API with Redux Toolkit
export const e4kTblSupplierSettings = createApi({
  reducerPath: 'e4kTblSupplierSettingsApi',
  // baseQuery: graphqlBaseQuery({
  //   baseUrl: 'http://127.0.0.1:8000/supplier/',
  // }),
  baseQuery : graphqlBaseQuery({ baseUrl : process.env.NEXT_PUBLIC_GRAPHQL_BASE_URL_Supplier}),
  tagTypes: ['e4ktblSuppliertSettings'],
  endpoints: (builder) => ({
    getSupplierSettings: builder.query({
      query: ({ companyid, settingid, businessid }) => ({
        body: {
          query: gql`
            query GetSupplierSettings($businessid: String!, $companyid: String!, $settingid: String!) {
              E4kTblsuppliersettings(businessid: $businessid, companyid: $companyid, settingid: $settingid) 
              
            }
          `,
          variables: { companyid, settingid, businessid },
        },
      }),
      providesTags: (result) =>
        result
          ? [
              ...result.E4kTblsuppliersettings.map(({ settingid }) => ({
                type: 'e4ktblSuppliertSettings',
                id: settingid,
              })),
              { type: 'e4ktblSuppliertSettings', id: 'LIST' },
            ]
          : [{ type: 'e4ktblSuppliertSettings', id: 'LIST' }],
    }),
    updateSupplierSetValue: builder.mutation({
      query: ({ businessid, companyid, settingid, value }) => ({
        body: {
          query: gql`
            mutation UpdateSupplierSetValue($businessid: String!, $companyid: String!, $settingid: String!, $value: String!) {
              E4kTblsuppliersetvalueupdate(businessid: $businessid, companyid: $companyid, settingid: $settingid, value: $value) {
                customersetvalues
              }
            }
          `,
          variables: { businessid, companyid, settingid, value },
        },
      }),
      invalidatesTags: (result, error, { settingid }) => [
        { type: 'e4ktblSuppliertSettings', id: settingid },
        { type: 'e4ktblSuppliertSettings', id: 'LIST' },
      ],
    }),
    
  }),
});

// Export hooks generated by createApi
export const { useGetSupplierSettingsQuery ,useUpdateSupplierSetValueMutation } = e4kTblSupplierSettings;
